{% set name = "conda_envfile" %}
{% set org = "tdegeus" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 71a65b42f5dce6eb6e6789141b4553c0d0847c56740b759222ed65c8bcfaabae

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - conda_envfile_merge = {{ name }}:_conda_envfile_merge_cli
    - conda_envfile_parse = {{ name }}:_conda_envfile_parse_cli
    - conda_envfile_restrict = {{ name }}:_conda_envfile_restrict_cli
    - conda_envfile_diff = {{ name }}:_conda_envfile_diff_cli

requirements:
  host:
    - pip
    - python >=3
    - setuptools_scm
  run:
    - click
    - jinja2
    - packaging
    - prettytable
    - python >=3
    - pyyaml

test:
  requires:
    - pip
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "import {{ name }}; assert {{ name }}.version == '{{ version }}'"
    - conda_envfile_merge --version | grep {{ version }}
    - conda_envfile_parse --version | grep {{ version }}
    - conda_envfile_restrict --version | grep {{ version }}
    - conda_envfile_diff --version | grep {{ version }}

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple command-line tools to clean / merge conda environment files.
  description: Simple command-line tools to clean / merge conda environment files.
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
